name: cryptosat
base: core20
version: '0.1'
summary: cryptosat
description: |
  cryptosat.

grade: devel
confinement: devmode

apps:
  init:
    command: init.sh
    daemon: simple
    refresh-mode: endure
    restart-condition: never

parts:
  cryptosat:
    plugin: dump
    source: dump
