name: cryptosat-gotham
base: core20
version: '0.1'
summary: cryptosat-gotham
description: |
  cryptosat-gotham.

grade: devel
confinement: devmode

parts:
  cryptosat-gotham:
    plugin: dump
    source: dump
